import Link from "next/link";
import type { Metadata } from "next";
import { ContentPage } from "@/components/content/content-page";
import { emailLink, selected2023, sources } from "@/lib/site-content";
export const metadata: Metadata = { title: "Sobre a Sertão Maker", description: "Conheça a atuação, a coordenação, a infraestrutura e os registros de resultados da Incubadora Sertão Maker no IFSertãoPE Campus Salgueiro." };

export default function Page() {
  return <ContentPage eyebrow="Empreendedorismo a partir do território" title="Conhecimento que encontra aplicação" intro="A Sertão Maker apoia ideias e negócios inovadores no IFSertãoPE Campus Salgueiro, conectando formação empreendedora, desenvolvimento de soluções e o Centro de Inovação Maker."
    blocks={[
      { title: "Nosso papel", text: "Ajudar pessoas a transformar problemas reais em propostas de negócio que possam ser testadas e desenvolvidas. A atuação combina conhecimento, tecnologia e colaboração para ampliar as oportunidades do território." },
      { title: "Como o apoio acontece", text: "O SerTão Inovador reúne etapas de pré-incubação e incubação. O acompanhamento parte do estágio da iniciativa e das regras de cada edição.", items: ["Formação e orientação empreendedora", "Mentorias e atividades práticas", "Testes e diagnóstico de maturidade", "Conexão com infraestrutura e parceiros"], link: { label: "Conhecer os programas", href: "/sertao-inovador" } },
      { title: "Coordenação e acompanhamento", text: "Marcelo Anderson Batista dos Santos é identificado como coordenador das incubadoras ISA/Sertão Maker nos documentos oficiais do programa de 2026, com referência à Portaria nº 10, de 12 de fevereiro de 2025.", items: ["Execução institucional pelo IFSertãoPE", "Rede de mentores e avaliadores organizada por edição", "Atendimento da incubadora para orientar cada iniciativa"], link: { label: "Consultar a identificação no documento de 2026 (PDF)", href: sources.coordination } },
      { title: "Infraestrutura no CIM", text: "O site institucional da Sertão Maker apresenta laboratório de Internet das Coisas (IoT), impressoras 3D e sala de podcast como infraestrutura de apoio. Esses espaços aproximam ideias de testes e protótipos.", items: ["IoT: sensores, dispositivos conectados e automação", "Impressão 3D: modelos e protótipos físicos", "Podcast e vídeo: apresentação e comunicação de projetos", "Utilização combinada conforme agenda e normas do espaço"], link: { label: "Entender como solicitar apoio", href: "/servicos" } },
    ]}
    cta={{ title: "Vamos conversar sobre o seu projeto?", label: "Falar com a incubadora", href: emailLink("Quero conhecer a Sertão Maker") }}>
    <section className="container content-section" aria-labelledby="history-title"><p className="eyebrow">Trajetória documentada</p><h2 id="history-title">Marcos da nossa atuação</h2><ol className="history-list"><li><span>2023</span><div><h3>Seleção para incubação</h3><p>O resultado da etapa 2 relaciona {selected2023.length} iniciativas selecionadas para o processo de incubação. Esse número registra uma seleção histórica, sem indicar o total atual de negócios ativos.</p><a className="text-link" href={sources.selection2023}>Consultar resultado oficial (PDF) →</a></div></li><li><span>2023</span><div><h3>Reconhecimento ao projeto Sigma</h3><p>Projeto desenvolvido no Campus Salgueiro, dentro da incubadora Maker, alcançou o terceiro lugar no Prêmio AgroInnova 2023.</p><a className="text-link" href={sources.sigma}>Ler notícia institucional →</a></div></li><li><span>2024</span><div><h3>SerTão Inovador em rede</h3><p>O IFSertãoPE divulgou a execução do SerTão Inovador powered by InovAtiva pelas incubadoras ISA e Sertão Maker, com parceiros de formação e apoio metodológico.</p><a className="text-link" href={sources.network2024}>Conhecer o registro dessa edição →</a></div></li><li><span>2026</span><div><h3>Novos ciclos de pré-incubação</h3><p>As chamadas 45/2026 e 122/2026 documentam as edições de pré-incubação do SerTão Inovador.</p><Link className="text-link" href="/oportunidades">Consultar editais e cronogramas →</Link></div></li></ol></section>
    <section className="container content-section" aria-labelledby="results-title"><p className="eyebrow">Resultados com referência</p><h2 id="results-title">Experiências que ajudam a contar essa história</h2><div className="editorial-grid"><article className="editorial-card"><h3>{selected2023.length} iniciativas selecionadas</h3><p>Resultado da etapa 2, publicado em 23 de janeiro de 2023. Indicador referente à seleção daquele ano.</p><a className="text-link" href={sources.selection2023}>Fonte do indicador (PDF) →</a></article><article className="editorial-card"><h3>3º lugar no AgroInnova</h3><p>Reconhecimento ao projeto Sigma em junho de 2023. Conheça a solução e o contexto da premiação.</p><Link className="text-link" href="/startups/sigma">Conhecer o caso →</Link></article></div></section>
  </ContentPage>;
}
