import type { Metadata } from "next";
import { ContentPage } from "@/components/content/content-page";
import { emailLink, featuredStartups, selected2023, selected2026, sources } from "@/lib/site-content";
export const metadata: Metadata = { title: "Startups e resultados | Sertão Maker", description: "Conheça as 28 startups aprovadas no ciclo de incubação 2026.1 do SerTão Inovador e registros históricos de projetos." };
export default function Page() {
  return <ContentPage eyebrow="Startups e resultados" title="Novas soluções a partir do Sertão" intro="Conheça a seleção mais recente de incubação do SerTão Inovador e experiências documentadas do ecossistema. Projetos que encontram apoio para dar seus próximos passos."
    blocks={[]}
    cta={{ title: "Seu projeto tem uma história para compartilhar?", label: "Enviar atualização do projeto", href: emailLink("Atualização de projeto para o portfólio — Sertão Maker") }}>
    <section className="container content-section content-section--first" id="ciclo-2026-1" aria-labelledby="current-startups-title"><p className="eyebrow">Aprovadas para incubação · 2026.1</p><h2 id="current-startups-title">Uma nova geração de negócios.</h2><p>O resultado final do edital nº 191/2025 reúne 28 startups aprovadas para o ciclo 2026.1. Entre elas:</p><div className="startup-grid">{featuredStartups.map(name => <article key={name}><span className="eyebrow">SerTão Inovador · 2026.1</span><h3>{name}</h3><p>Aprovada no resultado final de incubação.</p><a className="text-link" href={sources.incubationResult} target="_blank" rel="noopener noreferrer">Consultar resultado oficial ↗</a></article>)}</div><p className="source-note">A seleção é conjunta das incubadoras ISA e Sertão Maker. O resultado comprova a aprovação no programa; a distribuição entre incubadoras e o vínculo atual de cada startup devem ser confirmados com a equipe.</p><details className="selection-details"><summary>Ver todas as 28 startups aprovadas</summary><ul className="project-list">{selected2026.map(name => <li key={name}>{name}</li>)}</ul></details><div className="content-actions"><a className="text-link" href={sources.incubationResult} target="_blank" rel="noopener noreferrer">Resultado final 2026.1 (PDF) ↗</a><a className="text-link" href={sources.incubation} target="_blank" rel="noopener noreferrer">Edital e documentos da seleção ↗</a></div><p className="source-note">Documento datado de 26/01/2026 e publicado no portal institucional em 27/01/2026.</p></section>
    <section className="container content-section" aria-labelledby="selection-title"><p className="eyebrow">Seleção de 2023</p><h2 id="selection-title">Iniciativas relacionadas no resultado oficial</h2><p>O documento de 23 de janeiro de 2023 lista {selected2023.length} iniciativas selecionadas para o processo de incubação. Consulte a fonte para conhecer o contexto.</p><ul className="project-list">{selected2023.map(name => <li key={name}>{name}</li>)}</ul><a className="text-link" href={sources.selection2023}>Ver resultado da etapa 2 (PDF) →</a></section>
  </ContentPage>;
}
