import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content/content-page";
import { cycle, cycleStatus, emailLink, sources } from "@/lib/site-content";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Editais e oportunidades | Sertão Maker", description: "Edital 122/2026: requisitos, cronograma atualizado, documentos e canais oficiais da Pré-incubação SerTão Inovador 2026.2." };

export default function Page() {
  const status = cycleStatus();
  return <ContentPage eyebrow="Editais, seleções e resultados" title="Oportunidades para o próximo passo" intro="Confira as condições de participação e acompanhe os documentos de cada edição. Inscrição, seleção e resultado são etapas diferentes."
    blocks={[
      { id: "pre-incubacao-2026-2", title: "Pré-incubação 2026.2", text: "Edital nº 122/2026 · Programa SerTão Inovador. Apoio a projetos inovadores em ideação ou validação.", content: <><p><span className="status-label">{status.label}</span></p><dl className="facts-list"><div><dt>Vagas</dt><dd>Até 40 projetos; 50% reservadas a iniciativas vinculadas ao Sertão Pernambucano.</dd></div><div><dt>Formato e duração</dt><dd>Preferencialmente remoto, cerca de oito semanas de capacitação.</dd></div><div><dt>Custo</dt><dd>Atividades gratuitas, sem exigência de participação societária.</dd></div></dl><div className="content-actions"><a className="button button--primary" href={sources.preIncubation}>{status.action}</a>{!status.deadlinePassed && <a className="text-link" href="https://forms.gle/2PorH7Hrrvwhhtue7">Acessar formulário oficial →</a>}</div></> },
      { title: "Quem pode se inscrever", text: "O responsável deve ser maior de idade, residir em Pernambuco e ter titularidade ou capacidade de representar o projeto. CNPJ não é obrigatório.", items: ["Projeto inovador em fase de ideia ou validação", "Um projeto por responsável", "Se já houver empresa, conferir os critérios de porte no edital", "Não há exigência de vínculo estudantil com o IFSertãoPE"], link: { label: "Entender a pré-incubação", href: "/sertao-inovador/pre-incubacao" } },
      { title: "Cronograma publicado", text: "Datas previstas na retificação nº 02, de 6 de outubro de 2026, disponível no portal oficial. Novos comunicados podem alterar o calendário.", content: <><dl className="facts-list">{cycle.timeline.map(([stage, date]) => <div key={stage}><dt>{stage}</dt><dd>{date}</dd></div>)}</dl><p className="source-note">Conferência dos documentos: {cycle.checkedAt}. A retificação nº 02 prorroga as inscrições até {cycle.deadline} e atualiza as etapas da seleção. Consulte a execução do programa em caso de dúvida.</p></>, link: { label: "Ler a retificação nº 02 do cronograma (PDF)", href: sources.amendment } },
      { title: "O que será avaliado", text: "A seleção considera quatro dimensões. A nota mínima de aptidão é 60 pontos; a classificação segue as regras e a reserva de vagas do edital.", items: ["Equipe empreendedora", "Problema ou oportunidade de mercado", "Solução e proposta de valor", "Inovação e diferencial competitivo"], link: { label: "Preparar sua proposta", href: "/conteudos/prepare-sua-proposta" } },
      { title: "Documentos e comunicados", text: "Leia o regulamento completo e suas alterações. Resultados e orientações formais são publicados pelo IFSertãoPE.", content: <ul className="document-list"><li><a href={sources.preRegulation}>Edital nº 122/2026 completo (PDF)</a></li><li><a href={sources.amendment}>Retificação nº 02 (PDF)</a></li><li><a href={sources.preIncubation}>Resultados e novos comunicados no portal oficial</a></li></ul>, link: { label: "Enviar dúvida formal sobre a seleção", href: emailLink("Dúvida — Edital nº 122/2026", true) } },
      { title: "Depois da seleção", text: "Os selecionados recebem orientações no e-mail cadastrado, firmam o contrato de pré-incubação e participam das atividades obrigatórias.", items: ["Capacitação e sessões de mentoria", "Atividades práticas e diagnóstico de maturidade", "Apresentação no Demoday", "Pesquisas de acompanhamento após o ciclo"], link: { label: "Conhecer as atividades e compromissos", href: "/sertao-inovador/pre-incubacao" } },
    ]}
    cta={{ title: "Precisa esclarecer uma regra da seleção?", label: "Falar com a execução do programa", href: emailLink("Dúvida — Edital nº 122/2026", true) }}>
    <section className="container content-section" aria-labelledby="history-title"><p className="eyebrow">Histórico de edições</p><h2 id="history-title">Outras chamadas e documentos</h2><div className="editorial-grid"><article className="editorial-card"><span className="status-label status-label--neutral">Edição anterior · 2026.1</span><h3>Pré-incubação · Edital nº 45/2026</h3><p>Consulte resultados e documentos da seleção anterior. As regras e datas dessa edição não se aplicam automaticamente ao ciclo 2026.2.</p><a className="text-link" href={sources.previousCycle}>Consultar edição anterior →</a></article><article className="editorial-card"><span className="status-label status-label--neutral">Chamada de 2025/2026</span><h3>Incubação · Edital nº 191/2025</h3><p>Referência para o acompanhamento de negócios em validação ou operação inicial. Consulte as condições e atualizações oficiais.</p><Link className="text-link" href="/sertao-inovador/incubacao">Conhecer a incubação →</Link><p><a className="text-link" href={sources.incubationRegulation}>Ler regulamento publicado (PDF) →</a></p></article></div></section>
  </ContentPage>;
}
