import type { Metadata } from "next";
import Link from "next/link";
import { ContentPage } from "@/components/content/content-page";
import { cycle, guides, sources } from "@/lib/site-content";
export const metadata: Metadata = { title: "Guias e novidades | Sertão Maker", description: "Guias práticos para começar uma ideia, validar soluções e preparar propostas, além de informações oficiais do SerTão Inovador." };
export default function Page() {
  return <ContentPage eyebrow="Aprender, testar e empreender" title="Conteúdo para tirar ideias do papel" intro="Orientações práticas para quem está começando, escolhendo um programa ou preparando uma proposta. Encontre também documentos e acontecimentos do ecossistema."
    blocks={[]}
    cta={{ title: "Encontre o programa adequado ao seu estágio.", label: "Conhecer o SerTão Inovador", href: "/sertao-inovador" }}>
    <section className="container content-section content-section--first" aria-labelledby="guides-title"><p className="eyebrow">Biblioteca prática</p><h2 id="guides-title">Guias para o seu próximo passo</h2><div className="editorial-grid">{guides.map(guide => <article className="editorial-card" key={guide.slug}><p className="eyebrow">{guide.category} · {guide.readTime}</p><h3>{guide.title}</h3><p>{guide.intro}</p><Link className="text-link" href={"/conteudos/" + guide.slug}>Ler guia →</Link></article>)}</div></section>
    <section className="container content-section" aria-labelledby="news-title"><p className="eyebrow">Programa e ecossistema</p><h2 id="news-title">Documentos, agenda e histórias</h2><div className="editorial-grid"><article className="editorial-card"><p className="eyebrow">Seleção · atualização {cycle.checkedAt}</p><h3>Pré-incubação 2026.2</h3><p>Confira requisitos, prazo indicado na retificação e calendário da seleção.</p><Link className="text-link" href="/oportunidades">Ver edital e cronograma →</Link></article><article className="editorial-card"><p className="eyebrow">Agenda prevista · 16/12/2026</p><h3>Demoday da edição 2026.2</h3><p>Apresentação das soluções e conexão com atores do ecossistema. Data prevista no cronograma; programação e acesso serão comunicados pela execução. Não há inscrição pública de evento anunciada aqui.</p><a className="text-link" href={sources.preIncubation}>Acompanhar programação oficial →</a></article><article className="editorial-card"><p className="eyebrow">História · junho de 2023</p><h3>Sigma recebe reconhecimento no AgroInnova</h3><p>Conheça o projeto de tecnologia aplicada à agricultura familiar e a premiação registrada pelo IFSertãoPE.</p><Link className="text-link" href="/startups/sigma">Ler história →</Link></article><article className="editorial-card"><p className="eyebrow">Documentos · edição anterior</p><h3>Resultados da pré-incubação 2026.1</h3><p>Consulte os documentos e resultados publicados no portal institucional para a chamada nº 45/2026.</p><a className="text-link" href={sources.previousCycle}>Consultar publicação oficial →</a></article></div></section>
  </ContentPage>;
}
