import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { CycleSummary } from "@/components/content/cycle-summary";
import { preIncubationFaq } from "@/lib/site-content";

export const dynamic = "force-dynamic";
import { ArrowRight, ChevronDown } from "lucide-react";

export const metadata: Metadata = { title: "SerTão Inovador | Incubadora Sertão Maker", description: "Programa de formação, mentorias e conexões para transformar ideias do Sertão em projetos consistentes." };

const entregas = [
  { imagem: "/sertao-20.png", titulo: "Formação e mentorias", texto: "Sessões para discutir público, solução e decisões do projeto." },
  { imagem: "/sertao-19.png", titulo: "Estruturação da ideia", texto: "Organize problema, público e o benefício que sua solução oferece." },
  { imagem: "/sertao-18.png", titulo: "Conexões com parceiros", texto: "Apresente sua proposta e conheça atores do ecossistema." },
  { imagem: "/sertao-17.png", titulo: "Orientação para avançar", texto: "Defina hipóteses, testes e prioridades para desenvolver a iniciativa." },
];
const motivos = [
  { imagem: "/sertao-16.png", titulo: "Conheça seu público", texto: "Investigue o problema e reúna evidências com potenciais usuários." },
  { imagem: "/sertao-15.png", titulo: "Discuta decisões", texto: "Troque aprendizados com participantes e mentores." },
  { imagem: "/sertao-14.png", titulo: "Teste sua proposta", texto: "Use atividades práticas para revisar sua solução e modelo de negócio." },
  { imagem: "/sertao-13.png", titulo: "Planeje a continuidade", texto: "Identifique o que falta desenvolver e os critérios para uma próxima etapa." },
];
const jornada = [
  { numero: "01", imagem: "/sertao-18.png", titulo: "Conectar", texto: "Aproximamos pessoas, ideias e territórios, criando pontes entre talentos, desafios reais e oportunidades do Sertão." },
  { numero: "02", imagem: "/sertao-19.png", titulo: "Estruturar", texto: "Apoiamos o desenvolvimento das ideias, com formação prática, mentorias e ferramentas para transformar potencial em projetos consistentes." },
  { numero: "03", imagem: "/sertao-16.png", titulo: "Testar", texto: "Incentivamos a validação das soluções no contexto real, com foco nas necessidades do território e das pessoas que vivem nele." },
  { numero: "04", imagem: "/sertao-14.png", titulo: "Ajustar", texto: "Com base nos aprendizados, refinamos o modelo de negócio, fortalecemos a solução e preparamos para o crescimento sustentável." },
  { numero: "05", imagem: "/sertao-13.png", titulo: "Continuar", texto: "Seguimos junto, conectando com a rede de parceiros, novas oportunidades e o ecossistema de inovação." },
];
const faq = preIncubationFaq;

export default function Page() { return <main className="sertao-page">
  <section className="sertao-hero" aria-label="SerTão Inovador"><Image src="/sertao-capa-011.png" alt="SerTão Inovador — O Sertão cria, Pernambuco se conecta" width={2172} height={724} priority sizes="100vw" /></section>
  <section className="sertao-block sertao-about" aria-labelledby="about-title"><Image className="sertao-about-composition" src="/sertao-apresentacao.png" alt="Territórios vivos e gente do Sertão movendo o amanhã" width={4269} height={2400} sizes="100vw" /><div className="container sertao-about-grid"><div className="sertao-about-copy"><p className="sertao-kicker">Programa de inovação, empreendedorismo e território</p><h1 id="about-title"><span>O que é o</span><span className="sertao-title-red">SerTão Inovador?</span></h1><p>O SerTão Inovador é um programa do IFSertãoPE voltado ao desenvolvimento de iniciativas empreendedoras e inovadoras, conectando formação prática, acompanhamento e rede.</p><p>A execução é das incubadoras Sertão Maker e ISA — Incubadora do Semiárido, com apoio metodológico da Fundação Wadhwani.</p><strong>O Sertão cria, Pernambuco se conecta.</strong></div></div></section>
  <section className="sertao-block sertao-evolution" aria-labelledby="evolution-title"><div className="container sertao-evolution-heading"><h2 id="evolution-title"><span>Como a jornada</span> evolui</h2><p>Da ideia ao impacto real, uma jornada que conecta pessoas, conhecimento e oportunidades para o desenvolvimento do nosso território.</p></div><div className="container sertao-evolution-grid">{jornada.map((item) => <article key={item.numero}><span className="sertao-step-number">{item.numero}</span><Image src={item.imagem} alt="" width={1080} height={1080} /><div><h3>{item.titulo}</h3><p>{item.texto}</p></div></article>)}</div></section>
  <section className="sertao-block sertao-intro" aria-labelledby="encontra-title"><Image className="sertao-wide-art" src="/sertao-03.png" alt="Paisagem do Sertão: nosso território também inova" width={2172} height={724} sizes="100vw" /><div className="container sertao-section-copy"><h2 id="encontra-title"><span>O que você</span> encontra</h2><p>Atividades para compreender o problema, testar a solução e organizar uma proposta de negócio.</p></div><div className="container sertao-icon-grid">{entregas.map((item) => <article key={item.titulo}><Image src={item.imagem} alt="" width={1080} height={1080} /><h3>{item.titulo}</h3><p>{item.texto}</p></article>)}</div><Image className="sertao-divider-art" src="/sertao-06.png" alt="Gente que acredita move o Sertão" width={2172} height={724} sizes="100vw" /></section>
  <section className="sertao-block sertao-tracks" aria-labelledby="tracks-title"><div className="container sertao-section-copy"><h2 id="tracks-title"><span>Linhas de</span> formação</h2><p>Conteúdos e atividades pensados para cada etapa da jornada, com base nas reais necessidades de quem empreende no Sertão.</p></div><div className="container sertao-track-grid"><article className="sertao-track sertao-track--red"><div className="sertao-track-content"><h3>Pré-incubação</h3><p>Para quem tem uma ideia ou projeto em fase inicial e quer desenvolver melhor sua proposta.</p><ul><li>Problema e público</li><li>Testes com potenciais usuários</li><li>Proposta de valor e modelo de negócio</li><li>Apresentação e próximos passos</li></ul></div><Link href="/sertao-inovador/pre-incubacao">Conhecer a Pré-incubação <ArrowRight aria-hidden="true" /></Link></article><article className="sertao-track sertao-track--green"><div className="sertao-track-content"><h3>Incubação</h3><p>Para iniciativas mais maduras que precisam fortalecer mercado, operação, estratégia e crescimento.</p><ul><li>Posicionamento</li><li>Operação</li><li>Indicadores</li><li>Sustentabilidade</li><li>Conexões</li><li>Crescimento</li></ul></div><Link href="/sertao-inovador/incubacao">Conhecer a Incubação <ArrowRight aria-hidden="true" /></Link></article></div><Image className="sertao-line-art" src="/sertao-11.png" alt="Do Sertão para o mundo" width={2172} height={724} sizes="100vw" /></section>
  <section className="sertao-block sertao-cycle" aria-labelledby="cycle-title"><div className="container sertao-cycle-grid"><div><p className="sertao-kicker">Jornada atual</p><h2 id="cycle-title"><span>Ciclo de</span> Pré-incubação 2026.2</h2><p>Edição com até 40 projetos, cerca de oito semanas de capacitação e atividades preferencialmente remotas. As atividades são gratuitas e não exigem participação societária.</p><p>O calendário prevê capacitação a partir de 19 de outubro e Demoday em 16 de dezembro. Consulte o cronograma atualizado e as retificações na página de oportunidades.</p></div></div><div className="container sertao-audience"><Image src="/sertao-12.png" alt="Jovem observando o território do Sertão" width={2172} height={724} sizes="(max-width: 864px) 100vw, 48vw" /><div><p className="sertao-kicker">Pessoas que transformam</p><h2><span>Para</span> quem é</h2><p>Para projetos inovadores em ideação ou validação, representados por pessoas maiores de idade residentes em Pernambuco. Não é preciso ter CNPJ ou ser estudante do IFSertãoPE. Metade das vagas é reservada a projetos vinculados ao Sertão Pernambucano, conforme o edital.</p></div></div></section>
  <CycleSummary />
  <section className="sertao-block sertao-benefits" aria-labelledby="benefits-title"><div className="container sertao-section-copy"><h2 id="benefits-title"><span>Por que</span> participar</h2></div><div className="container sertao-benefit-grid">{motivos.map((item) => <article key={item.titulo}><Image src={item.imagem} alt="" width={1080} height={1080} /><h3>{item.titulo}</h3><p>{item.texto}</p></article>)}</div></section>
  <section className="sertao-block sertao-faq" aria-labelledby="faq-title"><div className="container sertao-faq-grid"><div><p className="sertao-kicker">Perguntas que aproximam novos começos</p><h2 id="faq-title"><span>Dúvidas</span> frequentes</h2></div><div>{faq.map(([pergunta, resposta]) => <details key={pergunta}><summary>{pergunta}<ChevronDown aria-hidden="true" /></summary><p>{resposta}</p></details>)}</div></div></section>
  <div className="sertao-final-band">
    <Image className="sertao-final-background" src="/sertao-rodape.png" alt="" width={1672} height={941} sizes="100vw" />
    <section className="sertao-block sertao-network" aria-labelledby="network-title"><div className="container"><p className="sertao-kicker">Uma rede que fortalece o território</p><h2 id="network-title"><span>Rede e</span> parceiros</h2><p>As instituições assumem papéis diferentes em cada edição: realização, execução, apoio metodológico ou conexão com o território. Consulte os vínculos documentados e as condições para colaborar.</p><p><Link className="text-link" href="/parcerias">Conheça os papéis na rede e proponha uma colaboração <ArrowRight aria-hidden="true" /></Link></p><Image className="sertao-partner-logos" src="/sertao-parceiros.png" alt="Instituições parceiras: Incubadora Sertão Maker, ISA, Wadhwani Foundation, CIM, IFSertãoPE, SEBRAE, Inova Salgueiro, Canoa Grande, Inova Araripe, FACAPE, UFRPE e Prefeitura de Salgueiro" width={6000} height={660} sizes="(max-width: 864px) 180vw, 70vw" /></div></section>
    <section className="sertao-cta" aria-labelledby="cta-title"><div><p>O Sertão cria, Pernambuco se conecta.</p><h2 id="cta-title">Inscrições e informações</h2><Link href="/oportunidades">Ver edital, prazo e resultados <ArrowRight aria-hidden="true" /></Link></div></section>
  </div>
</main>; }
