import type { Metadata } from "next";
import { ContentPage } from "@/components/content/content-page";
import { BenefitsSection } from "@/components/content/benefits-section";
import { emailLink, sources } from "@/lib/site-content";
export const metadata: Metadata = { title: "Serviços e infraestrutura | Sertão Maker", description: "Entenda os apoios de formação, mentoria, prototipagem e infraestrutura, as condições de acesso e como solicitar orientação." };
export default function Page() {
  return <ContentPage eyebrow="Apoio para desenvolver sua iniciativa" title="Do problema ao próximo teste" intro="Conheça os tipos de apoio da incubadora e a infraestrutura apresentada no CIM. A equipe orienta o caminho conforme o projeto, o programa e a disponibilidade."
    blocks={[
      { title: "Formação e mentoria", text: "Apoio oferecido nos programas: compreender o público, organizar a proposta de valor e definir prioridades do negócio.", items: ["Para participantes selecionados conforme o edital", "Atividades individuais ou coletivas conforme a edição", "No ciclo de pré-incubação 2026.2, as atividades são gratuitas"], link: { label: "Conhecer programas e ingresso", href: "/sertao-inovador" } },
      { title: "Prototipagem e impressão 3D", text: "Conexão com a infraestrutura do CIM para avaliar modelos e testes de produtos físicos. A impressão 3D pode ajudar a testar dimensões, encaixes e conceitos.", items: ["Informe o objetivo do teste, materiais e arquivos disponíveis", "Uso sujeito a avaliação técnica, agenda e normas", "Combine custos de materiais, responsabilidades e prazos antes do uso"], link: { label: "Consultar apoio à prototipagem", href: emailLink("Apoio à prototipagem e impressão 3D — Sertão Maker") } },
      { title: "IoT e automação", text: "Internet das Coisas (IoT) conecta dispositivos, como sensores, para coletar dados e apoiar decisões. O laboratório apresentado no site institucional apoia desenvolvimento e testes de soluções conectadas.", items: ["Apresente a aplicação e o estágio do projeto", "Necessidades de equipamentos e acompanhamento são avaliadas", "Acesso a infraestrutura depende de autorização e disponibilidade"], link: { label: "Consultar apoio técnico", href: emailLink("Projeto de IoT e automação — Sertão Maker") } },
      { title: "Comunicação e sala de podcast", text: "A infraestrutura apresentada pela incubadora inclui ambiente para gravação de podcasts, vídeos e conteúdos de projetos.", items: ["Informe objetivo, público e formato da gravação", "Confirme agenda, equipamentos e condições de uso", "Combine previamente autorização de imagem e publicação"], link: { label: "Consultar gravação e uso do espaço", href: emailLink("Uso da sala de podcast — Sertão Maker") } },
      { title: "Captação e conexões", text: "Orientação para identificar oportunidades e estruturar propostas, além de aproximação com redes e parceiros. Benefícios de terceiros dependem de elegibilidade e condições próprias.", items: ["Preparação e revisão de propostas", "Apresentação do negócio e aproximação com o ecossistema", "Créditos de nuvem e capacitações externas devem ser confirmados para cada projeto"], link: { label: "Conversar sobre oportunidades de apoio", href: emailLink("Captação e conexões — Sertão Maker") } },
      { title: "Propriedade intelectual e desenvolvimento conjunto", text: "A incubadora pode orientar o encaminhamento de dúvidas sobre proteção de criações. Projetos realizados conjuntamente com a instituição ou com sua infraestrutura podem exigir instrumento específico.", items: ["Explique a criação e o tipo de colaboração desejada", "Combine condições antes de iniciar desenvolvimento conjunto", "Consulte os responsáveis institucionais para orientações específicas"], link: { label: "Solicitar orientação e encaminhamento", href: emailLink("Orientação sobre propriedade intelectual — Sertão Maker") } },
    ]}
    cta={{ title: "Explique o que precisa testar ou desenvolver.", label: "Solicitar orientação sobre apoio", href: emailLink("Solicitação de apoio — Sertão Maker") }}>
    <BenefitsSection />
    <section className="container content-section" aria-labelledby="request-title"><p className="eyebrow">Como solicitar</p><h2 id="request-title">Três passos para iniciar a conversa</h2><ol className="history-list"><li><span>01</span><div><h3>Apresente a necessidade</h3><p>Envie seu nome, vínculo com o projeto, estágio da iniciativa e o objetivo do apoio.</p></div></li><li><span>02</span><div><h3>Combine as condições</h3><p>A equipe orienta sobre viabilidade, acesso, responsáveis, agenda e eventuais custos. O envio do pedido inicia a análise, sem reservar automaticamente equipamentos.</p></div></li><li><span>03</span><div><h3>Planeje a execução</h3><p>Após a confirmação, siga os procedimentos combinados para atividades, materiais, segurança e registro dos resultados.</p></div></li></ol><p className="source-note">Infraestrutura e tipos de apoio descritos no <a href={sources.oldSite}>site institucional da Sertão Maker</a>. Condições do programa no <a href={sources.preIncubation}>edital 122/2026</a>.</p></section>
  </ContentPage>;
}
